version: '3.9'

services:
  app:
    container_name: auction_be
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
    env_file:
      - .env
    command: yarn start:prod

  db:
    image: postgres:13-alpine
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    container_name: redis_server
    ports:
      - '6379:6379'

volumes:
  db-data:
